<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageId>GIBUblHelper</PackageId>
    <Description>GİB e-Fatura / e-Arşiv UBL-TR yardımcı kütüphanesi.</Description>
    <Authors>GIBUblHelper</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\corePackages\Core.Ubl.Envelope\Core.Ubl.EnvelopeSerialization.csproj" />
    <ProjectReference Include="..\corePackages\Core.Ubl.Tr\Core.Ubl.Tr.csproj" />
    <ProjectReference Include="..\corePackages\Core.Ubl.Processing\Core.Ubl.Processing.csproj" />
  </ItemGroup>

</Project>
