<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CS8618;CS8603;CS8625;CS8604;CS8602;CS8601;CS8600;CS0649;CS0108;CS0114</NoWarn>
  </PropertyGroup>

</Project>
